#
###################################
# Site wide configuration
####################################
#
title: Roshan Mehta
email: gmate.sunny@gmail.com
description: Roshan Mehta personal website.
url: https://gmatesunny.github.io/ # the base hostname & protocol for your site
keywords: ["Programming", "C++", "Python", "DistributedSystem", "HireMe", "Tutorials"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Paris
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  input: GFM
  hard_wrap: false
#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Roshan Mehta
  avatar: leonids-logo.png
  job: "C++ and Python Developer"
  bio: "A backend developer having master's degree in distributed systems with interest in secure scalable solution."
  email: gmate.sunny@gmail.com
  disqus-shortname: disqus_3LZbbKKNk6
  twitter:  #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-111509417-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: gmatesunny #username
  stackoverflow: /1900589/roshan-mehta #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: gmatesunny #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
